"""Public API for fitting and exporting reduced-form models."""

from .artifacts import (
    PipelineManifest,
    build_position_map,
    canonical_manifest_position_map_keys,
    canonical_manifest_top_level_keys,
    make_metadata_frame,
)
from .baselines import (
    ElasticNetBaseline,
    GBTBaseline,
    OracleOLSBaseline,
    PerStratumFirstOrderBaseline,
    PLSBaseline,
    RidgeBaseline,
    compare_baselines,
)
from .data import (
    StandardizationBundle,
    align_xy,
    combination_labels,
    ensure_id_columns,
    fit_standardizers,
    stratified_holdout_split,
    stratified_subset_by_combination,
)
from .feature_expansion import (
    FeatureExpansionResult,
    FeatureExpansionSpec,
    apply_feature_expansion,
    default_feature_expansion_spec,
    ordered_expanded_feature_names,
)
from .features import (
    KNOWN_TRANSFORMATIONS,
    CategoricalInputDecl,
    DesignMatrixResult,
    DesignMatrixSpec,
    build_design_matrix,
    canonical_module_from_factor_name,
    parse_selected_input_structure,
)
from .final_ols import (
    FinalOLSFitResult,
    build_postfit_artifacts,
    canonical_postfit_artifact_names,
    fit_final_ols,
    make_coefficient_matrix_frame,
    make_holdout_nrmse_summary,
    make_standardization_frame,
    postfit_artifact_table,
    predict_final_ols,
    select_support_via_refit,
    select_threshold_on_internal_validation,
)
from .metrics import (
    bootstrap_macro_nrmse_ci,
    build_output_eligibility_ledger,
    macro_nrmse_from_ledger,
    macro_nrmse_with_ref,
    make_null_mean_prediction,
)
from .regularized_screening import (
    ScreeningSelectionResult,
    fit_multitask_elastic_net_screen,
    screening_selection_table,
)
from .release_manifest import ReleaseManifest, build_manifest, verify_manifest
from .transforms import (
    DEFAULT_TRANSFORM_LIBRARY,
    INVERSE,
    LOGARITHMIC,
    QUADRATIC,
    SQRT,
    TransformDef,
    warn_nan_transforms,
)
from .viz_io import canonical_bundle_loader_keys, load_postfit_bundle, predict_from_postfit_bundle
from .workflow import CanonicalWorkflowRun, run_canonical_workflow, write_postfit_bundle

__all__ = [
    "DEFAULT_TRANSFORM_LIBRARY",
    "INVERSE",
    "KNOWN_TRANSFORMATIONS",
    "LOGARITHMIC",
    "QUADRATIC",
    "SQRT",
    "CanonicalWorkflowRun",
    "CategoricalInputDecl",
    "DesignMatrixResult",
    "DesignMatrixSpec",
    "ElasticNetBaseline",
    "FeatureExpansionResult",
    "FeatureExpansionSpec",
    "FinalOLSFitResult",
    "GBTBaseline",
    "OracleOLSBaseline",
    "PLSBaseline",
    "PerStratumFirstOrderBaseline",
    "PipelineManifest",
    "ReleaseManifest",
    "RidgeBaseline",
    "ScreeningSelectionResult",
    "StandardizationBundle",
    "TransformDef",
    "align_xy",
    "apply_feature_expansion",
    "bootstrap_macro_nrmse_ci",
    "build_design_matrix",
    "build_manifest",
    "build_output_eligibility_ledger",
    "build_position_map",
    "build_postfit_artifacts",
    "canonical_bundle_loader_keys",
    "canonical_manifest_position_map_keys",
    "canonical_manifest_top_level_keys",
    "canonical_module_from_factor_name",
    "canonical_postfit_artifact_names",
    "combination_labels",
    "compare_baselines",
    "default_feature_expansion_spec",
    "ensure_id_columns",
    "fit_final_ols",
    "fit_multitask_elastic_net_screen",
    "fit_standardizers",
    "load_postfit_bundle",
    "macro_nrmse_from_ledger",
    "macro_nrmse_with_ref",
    "make_coefficient_matrix_frame",
    "make_holdout_nrmse_summary",
    "make_metadata_frame",
    "make_null_mean_prediction",
    "make_standardization_frame",
    "ordered_expanded_feature_names",
    "parse_selected_input_structure",
    "postfit_artifact_table",
    "predict_final_ols",
    "predict_from_postfit_bundle",
    "run_canonical_workflow",
    "screening_selection_table",
    "select_support_via_refit",
    "select_threshold_on_internal_validation",
    "stratified_holdout_split",
    "stratified_subset_by_combination",
    "verify_manifest",
    "warn_nan_transforms",
    "write_postfit_bundle",
]

__version__ = "0.1.0"
