"""SLURM array job script generator for distributed BSM pipeline execution.

Generates ready-to-submit sbatch scripts from config + manifest.
Supports stage and reduce phases with dependency chains.

Usage (programmatic)::

    from bsm_rfm.distributed.slurm_array_runner import SlurmArrayRunner

    runner = SlurmArrayRunner(config, manifest_path, output_root)
    stage_script = runner.generate_stage_script("interaction_discovery")
    reduce_script = runner.generate_reduce_script("interaction_discovery", after_job_id=12345)
    runner.write_scripts(output_dir="/scratch/bsm/bsm_run/scripts")

Usage (CLI)::

    pixi run bsm-hpc-submit --config configs/hpc/kestrel_30k.yml --stage interaction_discovery
"""

from __future__ import annotations

import logging
import os
import stat
import subprocess
from pathlib import Path

from bsm_rfm.distributed.config_distributed import DistributedConfig
from bsm_rfm.distributed.manifest import ShardManifest, load_manifest, manifest_summary

logger = logging.getLogger(__name__)

_STAGE_SBATCH_TEMPLATE = """\
#!/bin/bash
#SBATCH --job-name=bsm_{stage}_{run_id}
#SBATCH --account={account}
#SBATCH --partition={partition}
#SBATCH --time={walltime}
#SBATCH --mem={memory_mb}M
#SBATCH --cpus-per-task={cpus_per_task}
#SBATCH --array=0-{max_task_idx}%{max_concurrent}
#SBATCH --output={log_dir}/bsm_{stage}_%A_%a.out
#SBATCH --error={log_dir}/bsm_{stage}_%A_%a.err
{requeue_line}
# ---------------------------------------------------------------------------
# BSM Manuscript Pipeline — SLURM Array Stage Runner
# Stage : {stage}
# Run ID: {run_id}
# Shards: {n_shards}
# Generated by bsm_rfm.distributed.slurm_array_runner
# ---------------------------------------------------------------------------

set -euo pipefail

export PIXI_HOME="{pixi_env_path}"
export PIXI_CACHE_DIR="{pixi_cache_dir}"

TASK_ID=${{SLURM_ARRAY_TASK_ID}}
MANIFEST="{manifest_path}"
OUTPUT_ROOT="{output_root}"
SCRATCH_ROOT="{scratch_root}"
RUN_ID="{run_id}"
STAGE="{stage}"

echo "[$(date -u +%Y-%m-%dT%H:%M:%SZ)] BSM shard ${{TASK_ID}} starting on $(hostname)"
echo "[$(date -u +%Y-%m-%dT%H:%M:%SZ)] SLURM_JOB_ID=${{SLURM_JOB_ID}}"

# Create scratch working directory for this task
WORK_DIR="${{SCRATCH_ROOT}}/${{RUN_ID}}/task-$(printf '%04d' ${{TASK_ID}})"
mkdir -p "${{WORK_DIR}}"

cd "{repo_root}"

# Run the shard worker via pixi
pixi run python tools/hpc_shard_worker.py \\
    --manifest "${{MANIFEST}}" \\
    --task-id "${{TASK_ID}}" \\
    --output-root "${{OUTPUT_ROOT}}" \\
    --work-dir "${{WORK_DIR}}" \\
    --stage "${{STAGE}}"

echo "[$(date -u +%Y-%m-%dT%H:%M:%SZ)] BSM shard ${{TASK_ID}} COMPLETE"
"""

_REDUCE_SBATCH_TEMPLATE = """\
#!/bin/bash
#SBATCH --job-name=bsm_reduce_{stage}_{run_id}
#SBATCH --account={account}
#SBATCH --partition={partition}
#SBATCH --time={reduce_walltime}
#SBATCH --mem={reduce_memory_mb}M
#SBATCH --cpus-per-task={cpus_per_task}
#SBATCH --output={log_dir}/bsm_reduce_{stage}_%j.out
#SBATCH --error={log_dir}/bsm_reduce_{stage}_%j.err
{dependency_line}
# ---------------------------------------------------------------------------
# BSM Manuscript Pipeline — SLURM Reduce Job
# Stage : {stage}
# Run ID: {run_id}
# Aggregates shard outputs into a single stage artifact
# ---------------------------------------------------------------------------

set -euo pipefail

export PIXI_HOME="{pixi_env_path}"
export PIXI_CACHE_DIR="{pixi_cache_dir}"

MANIFEST="{manifest_path}"
OUTPUT_ROOT="{output_root}"
STAGE="{stage}"
RUN_ID="{run_id}"

echo "[$(date -u +%Y-%m-%dT%H:%M:%SZ)] BSM reduce ${{STAGE}} starting on $(hostname)"

cd "{repo_root}"

pixi run python tools/hpc_reduce.py \\
    --manifest "${{MANIFEST}}" \\
    --output-root "${{OUTPUT_ROOT}}" \\
    --stage "${{STAGE}}"

echo "[$(date -u +%Y-%m-%dT%H:%M:%SZ)] BSM reduce ${{STAGE}} COMPLETE"
"""

_DIAGNOSTIC_SBATCH_TEMPLATE = """\
#!/bin/bash
#SBATCH --job-name=bsm_diag_{run_id}
#SBATCH --account={account}
#SBATCH --partition={debug_partition}
#SBATCH --time=00:30:00
#SBATCH --mem=16G
#SBATCH --cpus-per-task=4
#SBATCH --output={log_dir}/bsm_diag_%j.out
#SBATCH --error={log_dir}/bsm_diag_%j.err
# ---------------------------------------------------------------------------
# BSM Environment / Connectivity Smoke Test
# Run this first on a new cluster to validate the environment before submitting
# production array jobs.
# ---------------------------------------------------------------------------

set -euo pipefail

export PIXI_HOME="{pixi_env_path}"
export PIXI_CACHE_DIR="{pixi_cache_dir}"

echo "[$(date -u +%Y-%m-%dT%H:%M:%SZ)] Diagnostic run on $(hostname)"
echo "  PIXI_HOME=${{PIXI_HOME}}"
echo "  PIXI_CACHE_DIR=${{PIXI_CACHE_DIR}}"

cd "{repo_root}"

# Verify pixi environment is accessible
pixi run python -c \
    "import bsm_rfm; print('bsm_rfm OK'); import numpy, pandas, sklearn, shap; print('deps OK')"

# Print SLURM config summary
echo "  MaxArraySize=$(scontrol show config | grep MaxArraySize | awk '{{print $3}}')"
echo "  Partition info:"
sinfo -p {partition} --noheader -O partition,avail,nodes,cpus,memory,time

echo "[$(date -u +%Y-%m-%dT%H:%M:%SZ)] Diagnostic complete"
"""

_GPU_STAGE_SBATCH_TEMPLATE = """\
#!/bin/bash
#SBATCH --job-name=bsm_gpu_{stage}_{run_id}
#SBATCH --account={account}
#SBATCH --partition={gpu_partition}
#SBATCH --time={gpu_walltime}
#SBATCH --mem={gpu_host_memory_mb}M
#SBATCH --cpus-per-task={cpus_per_task}
#SBATCH --gpus-per-node={n_gpus}
#SBATCH --array=0-{max_task_idx}%{max_concurrent}
#SBATCH --output={log_dir}/bsm_gpu_{stage}_%A_%a.out
#SBATCH --error={log_dir}/bsm_gpu_{stage}_%A_%a.err
{requeue_line}
# ---------------------------------------------------------------------------
# BSM Manuscript Pipeline — SLURM GPU Array Stage Runner
# Stage : {stage}
# Run ID: {run_id}
# GPUs  : {n_gpus} x H100 (gpu-h100s partition)
# Shards: {n_shards}
# Uses XGBoost + SHAP GPU backend for interaction discovery acceleration.
# ---------------------------------------------------------------------------

set -euo pipefail

export PIXI_HOME="{pixi_env_path}"
export PIXI_CACHE_DIR="{pixi_cache_dir}"

# GPU-specific environment
export CUDA_VISIBLE_DEVICES=$(seq -s, 0 $(({n_gpus}-1)))
export BSM_INTERACTION_DEVICE="cuda"
export BSM_XGBOOST_TREE_METHOD="{xgboost_tree_method}"

TASK_ID=${{SLURM_ARRAY_TASK_ID}}
MANIFEST="{manifest_path}"
OUTPUT_ROOT="{output_root}"
SCRATCH_ROOT="{scratch_root}"
RUN_ID="{run_id}"
STAGE="{stage}"

echo "[$(date -u +%Y-%m-%dT%H:%M:%SZ)] BSM GPU shard ${{TASK_ID}} starting on $(hostname)"
echo "[$(date -u +%Y-%m-%dT%H:%M:%SZ)] CUDA_VISIBLE_DEVICES=${{CUDA_VISIBLE_DEVICES}}"
echo "[$(date -u +%Y-%m-%dT%H:%M:%SZ)] SLURM_JOB_ID=${{SLURM_JOB_ID}}"

# Verify GPU availability
nvidia-smi --query-gpu=name,memory.total \\
    --format=csv,noheader || echo "WARNING: nvidia-smi not available"

WORK_DIR="${{SCRATCH_ROOT}}/${{RUN_ID}}/task-$(printf '%04d' ${{TASK_ID}})"
mkdir -p "${{WORK_DIR}}"

cd "{repo_root}"

pixi run python tools/hpc_shard_worker.py \\
    --manifest "${{MANIFEST}}" \\
    --task-id "${{TASK_ID}}" \\
    --output-root "${{OUTPUT_ROOT}}" \\
    --work-dir "${{WORK_DIR}}" \\
    --stage "${{STAGE}}"

echo "[$(date -u +%Y-%m-%dT%H:%M:%SZ)] BSM GPU shard ${{TASK_ID}} COMPLETE"
"""

_GPU_DIAGNOSTIC_SBATCH_TEMPLATE = """\
#!/bin/bash
#SBATCH --job-name=bsm_gpu_diag_{run_id}
#SBATCH --account={account}
#SBATCH --partition={gpu_partition}
#SBATCH --time=00:30:00
#SBATCH --mem=64G
#SBATCH --cpus-per-task=16
#SBATCH --gpus-per-node=1
#SBATCH --output={log_dir}/bsm_gpu_diag_%j.out
#SBATCH --error={log_dir}/bsm_gpu_diag_%j.err
# ---------------------------------------------------------------------------
# BSM GPU Environment / CUDA Smoke Test
# Verifies GPU availability, XGBoost GPU support, and SHAP GPU backend
# before submitting production GPU array jobs.
# ---------------------------------------------------------------------------

set -euo pipefail

export PIXI_HOME="{pixi_env_path}"
export PIXI_CACHE_DIR="{pixi_cache_dir}"

echo "[$(date -u +%Y-%m-%dT%H:%M:%SZ)] GPU diagnostic run on $(hostname)"

# GPU info
nvidia-smi
echo ""

cd "{repo_root}"

# Verify bsm_rfm and GPU dependencies
pixi run python - <<'PYEOF'
import bsm_rfm
print(f"bsm_rfm OK: {{bsm_rfm.__file__}}")

import numpy as np
print(f"numpy {{np.__version__}}")

try:
    import xgboost as xgb
    print(f"xgboost {{xgb.__version__}}")
    dtrain = xgb.DMatrix(np.random.rand(100, 10), label=np.random.rand(100))
    params = {{"device": "cuda", "tree_method": "hist", "n_estimators": 5}}
    bst = xgb.train(params, dtrain, num_boost_round=5)
    print("XGBoost GPU: OK")
except Exception as e:
    print(f"XGBoost GPU: FAILED — {{e}}")

try:
    import shap
    print(f"shap {{shap.__version__}}")
except ImportError:
    print("shap: not installed")

try:
    import cupy as cp
    print(f"cupy {{cp.__version__}}, GPU: {{cp.cuda.Device().id}}")
    a = cp.zeros((1000, 1000))
    print("CuPy matmul: OK")
except ImportError:
    print("cupy: not installed (optional)")

from bsm_rfm.distributed.gpu_scoring import detect_device
device = detect_device("auto")
print(f"Detected device: {{device}}")
PYEOF


echo "[$(date -u +%Y-%m-%dT%H:%M:%SZ)] GPU diagnostic complete"
"""


class SlurmArrayRunner:
    """Generate SLURM sbatch scripts for distributed BSM pipeline execution.

    Parameters
    ----------
    config
        Distributed execution configuration.
    manifest_path
        Path to the shard manifest JSONL file.
    output_root
        Root directory for shard outputs (must be on shared filesystem).
    repo_root
        Absolute path to the BSM repository root (where pixi.toml lives).
        Defaults to current working directory.
    """

    def __init__(
        self,
        config: DistributedConfig,
        manifest_path: str | Path,
        output_root: str | Path,
        repo_root: str | Path | None = None,
    ):
        self.config = config
        self.manifest_path = Path(manifest_path)
        self.output_root = Path(output_root)
        self.repo_root = Path(repo_root) if repo_root else Path.cwd()

        # Validate config before generating scripts
        errors = config.validate()
        if errors:
            raise ValueError(f"Invalid DistributedConfig: {errors}")

        self._shards: list[ShardManifest] = []
        if self.manifest_path.exists():
            self._shards = load_manifest(self.manifest_path)

    @property
    def n_shards(self) -> int:
        """Number of shards in the manifest."""
        return len(self._shards)

    def _common_vars(self, stage: str) -> dict:
        cfg = self.config
        slurm = cfg.slurm
        kestrel = cfg.kestrel
        spill = cfg.spill
        gpu = cfg.gpu

        log_dir = slurm.resolve_log_dir(cfg.run_id)
        scratch_root = os.path.expandvars(spill.scratch_root)

        return {
            "stage": stage,
            "run_id": cfg.run_id,
            "account": slurm.account,
            "partition": slurm.partition,
            "walltime": slurm.walltime,
            "memory_mb": slurm.memory_gb * 1024,
            "cpus_per_task": slurm.cpus_per_task,
            "max_task_idx": max(0, self.n_shards - 1),
            "max_concurrent": slurm.max_concurrent_array_tasks,
            "log_dir": log_dir,
            "requeue_line": (
                "#SBATCH --requeue"
                if slurm.requeue
                else "# --requeue disabled (Kestrel PreemptMode=OFF)"
            ),
            "pixi_env_path": cfg.pixi_env_path,
            "pixi_cache_dir": kestrel.pixi_cache_dir,
            "manifest_path": str(self.manifest_path.resolve()),
            "output_root": str(self.output_root.resolve()),
            "scratch_root": scratch_root,
            "repo_root": str(self.repo_root.resolve()),
            "n_shards": self.n_shards,
            "debug_partition": kestrel.debug_partition,
            # GPU vars
            "gpu_partition": gpu.gpu_partition,
            "gpu_walltime": gpu.gpu_walltime,
            "n_gpus": gpu.n_gpus,
            "gpu_host_memory_mb": slurm.memory_gb * 1024,
            "xgboost_tree_method": gpu.xgboost_tree_method,
        }

    def generate_stage_script(self, stage: str) -> str:
        """Generate a SLURM array sbatch script for a pipeline stage.

        Parameters
        ----------
        stage
            Pipeline stage name (e.g. 'interaction_discovery').

        Returns
        -------
        str
            Complete sbatch script content.
        """
        if self.n_shards == 0:
            raise ValueError("No shards in manifest — run build_manifest() first")
        return _STAGE_SBATCH_TEMPLATE.format(**self._common_vars(stage))

    def generate_reduce_script(
        self,
        stage: str,
        after_job_id: int | None = None,
        reduce_walltime: str = "02:00:00",
        reduce_memory_gb: int = 32,
    ) -> str:
        """Generate a SLURM reduce job sbatch script.

        The reduce job aggregates shard outputs into a single stage artifact.
        It is submitted with a dependency on the array job so it runs only
        after all array tasks complete.

        Parameters
        ----------
        stage
            Pipeline stage name.
        after_job_id
            SLURM job ID of the array job to depend on. If provided, adds
            #SBATCH --dependency=afterok:<job_id>.
        reduce_walltime
            Walltime for the reduce job.
        reduce_memory_gb
            Memory (GB) for the reduce job.

        Returns
        -------
        str
            Complete sbatch script content.
        """
        vars_ = self._common_vars(stage)
        vars_["reduce_walltime"] = reduce_walltime
        vars_["reduce_memory_mb"] = reduce_memory_gb * 1024
        if after_job_id:
            vars_["dependency_line"] = f"#SBATCH --dependency=afterok:{after_job_id}"
        else:
            vars_["dependency_line"] = "# No dependency (submit after array job)"
        return _REDUCE_SBATCH_TEMPLATE.format(**vars_)

    def generate_diagnostic_script(self) -> str:
        """Generate a smoke-test diagnostic sbatch script."""
        return _DIAGNOSTIC_SBATCH_TEMPLATE.format(**self._common_vars("diagnostic"))

    def generate_gpu_stage_script(self, stage: str) -> str:
        """Generate a GPU-accelerated SLURM array sbatch script.

        Targets the GPU partition (gpu-h100s on Kestrel) and sets
        BSM_INTERACTION_DEVICE=cuda so the shard worker uses the
        XGBoost + SHAP GPU backend for interaction discovery.

        Parameters
        ----------
        stage
            Pipeline stage name. GPU acceleration is most effective for
            interaction_discovery.

        Returns
        -------
        str
            Complete sbatch script content.
        """
        if self.n_shards == 0:
            raise ValueError("No shards in manifest — run build_manifest() first")
        if not self.config.gpu.enabled:
            raise ValueError(
                "GPU script requested but config.gpu.enabled is False. "
                "Set distributed.gpu.enabled: true in your config."
            )
        return _GPU_STAGE_SBATCH_TEMPLATE.format(**self._common_vars(stage))

    def generate_gpu_diagnostic_script(self) -> str:
        """Generate a GPU environment smoke-test sbatch script."""
        return _GPU_DIAGNOSTIC_SBATCH_TEMPLATE.format(**self._common_vars("gpu_diagnostic"))

    def write_scripts(
        self,
        output_dir: str | Path,
        stage: str = "interaction_discovery",
        reduce_walltime: str = "02:00:00",
        reduce_memory_gb: int = 32,
    ) -> dict[str, Path]:
        """Write all sbatch scripts to output_dir and make them executable.

        Parameters
        ----------
        output_dir
            Directory to write scripts into (created if needed).
        stage
            Pipeline stage to target.
        reduce_walltime
            Walltime for the reduce job.
        reduce_memory_gb
            Memory (GB) for the reduce job.

        Returns
        -------
        dict[str, Path]
            Mapping of script name → absolute path.
        """
        out = Path(output_dir)
        out.mkdir(parents=True, exist_ok=True)

        scripts = {}
        if self.n_shards > 0:
            stage_script = out / f"submit_{stage}_array.sh"
            stage_script.write_text(self.generate_stage_script(stage))
            _make_executable(stage_script)
            scripts["stage"] = stage_script

            reduce_script = out / f"submit_{stage}_reduce.sh"
            reduce_script.write_text(
                self.generate_reduce_script(
                    stage,
                    reduce_walltime=reduce_walltime,
                    reduce_memory_gb=reduce_memory_gb,
                )
            )
            _make_executable(reduce_script)
            scripts["reduce"] = reduce_script

            # GPU scripts (when GPU is enabled in config)
            if self.config.gpu.enabled:
                gpu_script = out / f"submit_{stage}_gpu_array.sh"
                gpu_script.write_text(self.generate_gpu_stage_script(stage))
                _make_executable(gpu_script)
                scripts["gpu_stage"] = gpu_script

        diag_script = out / "submit_diagnostic.sh"
        diag_script.write_text(self.generate_diagnostic_script())
        _make_executable(diag_script)
        scripts["diagnostic"] = diag_script

        if self.config.gpu.enabled:
            gpu_diag_script = out / "submit_gpu_diagnostic.sh"
            gpu_diag_script.write_text(self.generate_gpu_diagnostic_script())
            _make_executable(gpu_diag_script)
            scripts["gpu_diagnostic"] = gpu_diag_script

        submit_all = out / "submit_all.sh"
        submit_all.write_text(_make_submit_all_script(scripts, stage))
        _make_executable(submit_all)
        scripts["submit_all"] = submit_all

        logger.info("[slurm] wrote %d scripts to %s", len(scripts), out)
        return scripts

    def status(self) -> dict[str, int]:
        """Return a summary of shard statuses from the manifest."""
        if not self._shards:
            return {}
        return manifest_summary(self._shards)

    def submit(
        self,
        script_path: str | Path,
        dry_run: bool = False,
    ) -> int | None:
        """Submit an sbatch script and return the job ID.

        Parameters
        ----------
        script_path
            Path to the sbatch script.
        dry_run
            If True, print the sbatch command but do not execute it.

        Returns
        -------
        int or None
            SLURM job ID, or None if dry_run=True or submission fails.
        """
        cmd = ["sbatch", str(script_path)]
        if dry_run:
            print(f"[dry-run] Would submit: {' '.join(cmd)}")
            return None
        try:
            result = subprocess.run(cmd, capture_output=True, text=True, check=True)
            # sbatch output: "Submitted batch job 12345"
            job_id = int(result.stdout.strip().split()[-1])
            logger.info("[slurm] submitted job %d from %s", job_id, script_path)
            return job_id
        except subprocess.CalledProcessError as e:
            logger.error("[slurm] sbatch failed: %s\n%s", e, e.stderr)
            raise


def _make_executable(path: Path) -> None:
    path.chmod(path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)


def _make_submit_all_script(scripts: dict[str, Path], stage: str) -> str:
    stage_path = scripts.get("stage")
    gpu_stage_path = scripts.get("gpu_stage")
    reduce_path = scripts.get("reduce")
    diag_path = scripts.get("diagnostic")
    primary_stage_path = gpu_stage_path or stage_path

    lines = [
        "#!/bin/bash",
        "# Submit all BSM HPC jobs for stage: " + stage,
        "# Run this from the repo root after pixi install --locked",
        "set -euo pipefail",
        "",
    ]
    if diag_path:
        lines += [
            "# Step 0: Smoke test (optional — run first on a new cluster)",
            f"# sbatch {diag_path.name}",
            "",
        ]
    if primary_stage_path:
        lines += [
            f"ARRAY_JOB_ID=$(sbatch --parsable {primary_stage_path.name})",
            'echo "Submitted array job: $ARRAY_JOB_ID"',
            "",
        ]
    if reduce_path:
        lines += [
            f"REDUCE_JOB_ID=$(sbatch --parsable --dependency=afterok:$ARRAY_JOB_ID {reduce_path.name})",  # noqa: E501
            'echo "Submitted reduce job: $REDUCE_JOB_ID (depends on $ARRAY_JOB_ID)"',
            "",
            "echo 'Monitor progress:'",
            "echo '  squeue -u $USER'",
            "echo '  tail -f logs/bsm_" + stage + "_*.out'",
        ]
    return "\n".join(lines) + "\n"
